[project]
name = "dev-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=1.0.1",
    "pydantic-ai-slim[openai]>=1.0.1",
]
